Implementation of different sorting methods, factory method and appli…
Luckyakalucka/java-labs-2 pull request #1
Opened 2023-10-16 13:19 UTC by Luckyakalucka

…cation to test sorting methods on different parameters.

Count: 10
6 1 4 1 0 3 9 3 6 4 
BubbleSorter:      0 ms | 0 1 1 3 3 4 4 6 6 9 
 MergeSorter:      0 ms | 0 1 1 3 3 4 4 6 6 9 
 QuickSorter:      0 ms | 0 1 1 3 3 4 4 6 6 9 
 ShellSorter:      0 ms | 0 1 1 3 3 4 4 6 6 9

2023-10-17 05:43 UTC, Skuratovskyi requested changes
Додайте будь-ласка скріншот виводу програми в корінь проекту

2023-10-17 05:43 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/Main.java
> +        for (int i = 0; i < limit; i++) {
в цьому методі можна зробити "магію". Тому що операція конкатенації у рядку 43 у циклі - не дуже гарно виглядає. Рядки в java - immutable, і на кожну конкатенацію ви створюєте тимчасову змінну. 
Можна спочатку отримати необхідну частину списку List copy = arrayList.subList(startIndex, endIndex);, а потім викликати String a = String.join(" ", copy); Після цього викликаєте System.out.println(a); без усіляких циклів.

2023-10-17 05:43 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/sorter/QuickSorter.java
> +            quickSort(arr, pi + 1, high);
а сам елемент pi  у вас в сортуванні участі не приймає?

2023-10-17 05:43 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/sorter/BubbleSorter.java
> +        return input;
схоже на те, що ви в цьому методі сортуєте вхідний масив. І решта методів отримує його вже відсортованим. Тому не видно проблем, наприклад, з quickSort

2023-10-17 05:43 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/sorter/MergeSorter.java
> +        List<Integer> right = input.subList(middle, input.size());
а тут у вас один елемент middle приймає участь в обох підмасивах - left і right.

2023-10-17 05:47 UTC, Luckyakalucka commented on src/main/java/ua/luckyakalucka/sorter/MergeSorter.java
> +        List<Integer> right = input.subList(middle, input.size());
public List subList(int fromIndex, int toIndex)
    fromIndex - нижня кінцева точка (включно) підсписку
    toIndex - верхня кінцева точка (виключено) підсписку

2023-10-17 05:50 UTC, Luckyakalucka commented on src/main/java/ua/luckyakalucka/sorter/BubbleSorter.java
> +        return input;
// src/ua/luckyakalucka/Main.java

for (SortingType type: new SortingType[]{BubbleSorter, MergeSorter, QuickSorter, ShellSorter}) { // BubbleSorter - долго піздец
                Sorter sorter = SorterFactory.choiceSorterMethod(type);
                ArrayList<Integer> input = new ArrayList<>(arrayList);
                timeSorting(input, sorter, type.toString());

            }
            
Кожну ітерацію по SortingType копіюється масив рядком:
ArrayList<Integer> input = new ArrayList<>(arrayList);

2023-10-17 06:00 UTC, Luckyakalucka commented on src/main/java/ua/luckyakalucka/sorter/QuickSorter.java
> +            quickSort(arr, pi + 1, high);
pi - опорний елемент
Взагалі з [цього ](https://www.javatpoint.com/quick-sort)сайту брав алгоритм та переписував його на мову Java

2023-10-17 06:01 UTC, Luckyakalucka commented on src/main/java/ua/luckyakalucka/Main.java
> +        for (int i = 0; i < limit; i++) {
Дякую, у подальшему буду використовувати, і в цьому коді заміню

2023-10-17 06:06 UTC, Luckyakalucka commented
> Додайте будь-ласка скріншот виводу програми в корінь проекту

![Зображення](https://github.com/Luckyakalucka/java-labs-2/assets/60516550/e4f55755-8798-4142-a3f4-e474b5c7db07), також додав у root проєкту, але не знаю як додану у інснуючий пул реквест комміт

2023-10-17 06:19 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/sorter/MergeSorter.java
> +        List<Integer> right = input.subList(middle, input.size());
питання знято

2023-10-17 06:19 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/sorter/BubbleSorter.java
> +        return input;
питання знято

2023-10-17 06:23 UTC, Skuratovskyi commented on src/main/java/ua/luckyakalucka/sorter/QuickSorter.java
> +            quickSort(arr, pi + 1, high);
питання знято

2023-10-17 07:07 UTC, Luckyakalucka commented on src/main/java/ua/luckyakalucka/Main.java
> +        for (int i = 0; i < limit; i++) {
`
private static void printArray(ArrayList<Integer> arrayList) {
        int limit = Math.min(arrayList.size(), maxPrintElem);
        List printList = arrayList.subList(0, limit);
        String printString = (String) printList.stream().map(o -> o.toString()).collect(Collectors.joining(" "));
        System.out.println(printString);
    }
`

Переписав без циклів, але не таким методом як Ви написали - String.join очікує, що елементи в printList будуть об'єктами типу CharSequence, такими як рядки (String), а не цілими числами (Integer).

2023-10-24 05:16 UTC, Skuratovskyi approved these changes

2023-10-24 05:17 UTC, merged